### ISSUE TITLE
Support absolute paths for requirements.txt

### ISSUE THREAD

**Issue by 4U6U57** [sobolevn/dotbot-pip#9]
Get the error `Requirements file does not exist.` when specifying an absolute path to a requirements file.

Example YAML:
```yaml
- git:
    '~/company-repo':
      url: 'git@gitlab.org:company/company-repo.git'
      description: company repo

- pip:
    file: ~/company-repo/acceptance-tests/requirements.txt
```

Edit: In addition, even with a check for `os.path.isabs`, two separate issues are expanding `~` (`os.path.expanduser`) and `$HOME` (`os.path.expandvars`). Not sure if there's something in Python that would do all of that out of the box.
